{:loc [14 10],
 :dir 1.5707963267948966,
 :soundtrack ["Music/06_Ghosts_I.ogg"]
 :walls
 #{[16 7] [15 7] [16 8] [14 7] [16 9] [13 7] [16 10] [17 11] [18 12]
   [16 11] [12 8] [17 13] [12 9] [14 11] [16 13] [12 10] [13 11]
   [14 12] [15 13]},
 :wall-mat "Textures/paper1.jpg",
 :widgets
 [{:name :text-screen,
   :answers
   {:direction -1.5761726190806056,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nPROGRAMMED BY ZACH LITTRELL\n\nTHANK YOU FOR PLAYING!",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 8,
    :x 14,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -0.0,
    :protocol :none,
    :text
    "TECHNOLOGY\n==========\n\nBUILT USING:\n\nClojure\n\nleiningen\n\nvim",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 9,
    :x 13,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -3.081961940458624,
    :protocol :none,
    :text
    "LIBRARIES\n=========\n\nPOWERED BY:\n\ninstaparse\n\nJFugue\n\njMonkeyEngine\n\nNiftyGui\n\nSeesaw\n",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 9,
    :x 15,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text
    "TESTERS\n================\n\nYOUR NAME HERE!\n\nOLIVIA BRUNDAGE\n\nDR. SPENCER HAMBLEN\n\nIAN LEVEE",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 12,
    :x 15,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 3.1328592511813667,
    :protocol :none,
    :text "SOUNDTRACK\n=========\n\n06 Ghosts I - Nine Inch Nails",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 12,
    :x 17,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :id "",
    :target-ids []}}]}
