{:loc [14 6],
 :dir -1.6384893494888655,
 :walls
 #{[16 5] [15 5] [16 6] [18 8] [19 9] [14 5] [16 7] [17 8] [19 10]
   [13 5] [16 8] [19 11] [12 5] [16 9] [19 12] [12 6] [14 8] [16 10]
   [18 12] [12 7] [16 11] [12 8] [17 13] [12 9] [14 11] [16 13] [12 10]
   [13 11] [14 12] [15 13]},
 :wall-mat "Textures/paper1.jpg",
 :soundtrack ["Music/06_Ghosts_I.ogg"],
 :widgets
 [{:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nPOGGIO\n\nPROGRAMMED BY ZACH LITTRELL\n\nTHANK YOU FOR PLAYING!",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 7,
    :x 14,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -0.0,
    :protocol :none,
    :text
    "TECHNOLOGY\n==========\n\nBUILT USING:\n\nClojure\n\nleiningen\n\nvim",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 9,
    :x 13,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -3.081961940458624,
    :protocol :none,
    :text
    "LIBRARIES\n=========\n\nPOWERED BY:\n\ninstaparse\n\nJFugue\n\njMonkeyEngine\n\nNiftyGui\n\nSeesaw\n",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 9,
    :x 15,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -1.5857952019467474,
    :protocol :none,
    :text
    "MODELS\n================\n\nMODELS WERE CREATED BY:\n\nCannon - chrisbreen1995\n\nEarth - Michael Kurinnoy\n\nGramophone - MaryLycan\n\nPenguin - Phelippeau Rudy\n\nHoop - BucketOBolts",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 9,
    :x 17,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -1.5939403417288784,
    :protocol :none,
    :text
    "TEXTURES\n================\n\nTEXTURES PROVIDED BY:\n\nSound Barrier - Tutorials For Blender 3D\n\nWood, Tile - PlainTextures\n\nWater/Glass Wall - Jattenalle\n\nPaper Wall - darkwood67",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 9,
    :x 18,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text
    "TESTERS\n================\n\nYOUR NAME HERE!\n\nOLIVIA BRUNDAGE\n\nDR. SPENCER HAMBLEN\n\nZACH HECKLE\n\nJEFFREY KANE\n\nIAN LEVEE\n\nJOSIAH NUSBAUM\n\nnetsky08",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 12,
    :x 15,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 3.1328592511813667,
    :protocol :none,
    :text
    "SOUNDTRACK\n=========\n\n06 Ghosts I - Nine Inch Nails\n\n16 - Japan Tsunami Fundraiser - ambient_samurai-Senses_Planned_For_Oblivion",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 12,
    :x 17,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}]}
