{:loc [20 31],
 :dir 1.5707963267948966,
 :soundtrack ["Music/06_Ghosts_I.ogg"] 
 :walls
 #{[19 18] [20 19] [19 19] [22 22] [19 20] [22 23] [22 24] [23 25]
   [18 21] [23 26] [24 27] [18 22] [20 24] [20 25] [21 26] [23 28]
   [29 2] [17 23] [19 25] [20 26] [22 28] [28 2] [29 3] [17 24] [18 25]
   [19 26] [21 28] [27 2] [29 4] [16 24] [17 25] [18 26] [21 29] [29 5]
   [15 24] [17 26] [19 28] [21 30] [26 3] [29 6] [30 7] [13 23] [14 24]
   [18 28] [19 29] [21 31] [26 4] [27 5] [29 7] [30 8] [15 26] [17 28]
   [19 30] [26 5] [28 7] [30 9] [12 24] [14 26] [15 27] [16 28] [19 31]
   [20 32] [25 5] [27 7] [30 10] [12 25] [13 26] [15 28] [19 32] [24 5]
   [26 7] [30 11] [31 12] [32 13] [23 5] [25 7] [26 8] [30 12] [32 14]
   [22 5] [24 7] [25 8] [29 12] [32 15] [21 5] [24 8] [26 10] [32 16]
   [21 6] [25 10] [26 11] [30 15] [32 17] [21 7] [24 10] [26 12]
   [27 13] [29 15] [30 16] [32 18] [21 8] [23 10] [27 14] [28 15]
   [30 17] [32 19] [21 9] [22 10] [27 15] [29 17] [32 20] [26 15]
   [28 17] [31 20] [32 21] [25 15] [27 17] [28 18] [32 22] [24 15]
   [25 16] [26 17] [28 19] [23 15] [25 17] [28 20] [31 23] [22 15]
   [26 19] [28 21] [30 23] [25 19] [27 21] [29 23] [21 16] [24 19]
   [26 21] [28 23] [20 16] [23 19] [24 20] [27 23] [22 19] [23 20]
   [24 21] [26 23] [19 17] [23 21] [24 22] [25 23]},
 :wall-mat "Textures/paper1.jpg",
 :widgets
 [{:name :text-screen,
   :answers
   {:direction -1.5632964674151508,
    :protocol :none,
    :text "EXIT",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 6,
    :x 22,
    :success-text "",
    :font-size 2.0,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -1.5570357275127085,
    :protocol :open,
    :text
    "POGGIO INSTITUTE\n================\n\nSEND true TO EXIT.\n\n",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 6,
    :x 23,
    :success-text "\nGOOD JOB. TAKE A BREAK.",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? true,
    :success? "message",
    :error-text "",
    :docstring
    "Takes:a boolean called message.\nReturns: Opens the exit when message is true.",
    :distance 40,
    :id "",
    :target-ids ["Exit Door"]}}
  {:name :glass-door,
   :answers
   {:z 6,
    :x 24,
    :id "Exit Door",
    :direction -3.066732805879026,
    :distance 8.0,
    :movement :up,
    :speed 6.0,
    :time 0.0}}
  {:name :globule-receiver,
   :answers
   {:z 8,
    :x 27,
    :id "Hoop Epsilon",
    :direction -1.5647723032787262,
    :y 1,
    :target-ids ["Door Epsilon"],
    :protocol :open-on-pattern,
    :pattern ["color 255 255 255"]}}
  {:name :globule-receiver,
   :answers
   {:z 8,
    :x 28,
    :id "Hoop Zeta",
    :direction -1.547363116915429,
    :y 1,
    :target-ids ["Door Zeta"],
    :protocol :open-on-pattern,
    :pattern ["color 0 0 0"]}}
  {:name :text-screen,
   :answers
   {:direction 3.1139499269470687,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nTHE DOORS OPEN WHEN:\n\nTHE FIRST HOOP RECEIVES (color 255 255 255)\n\nTHE SECOND HOOP RECEIVES (color 0 0 0)",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 8,
    :x 29,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 0.011049274079368817,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nGOOD JOB WITH HANDLING THE FUNCTION JUNCTION. \n\nSTUDIES HAVE SHOWN THAT MONKEYS NEED REST BETWEEN LEARNING NEW THINGS AND HIGH STRESS SITUATIONS,\n\nLEST THEY HAVE A MENTAL BREAKDOWN.\n\nSO TAKE SOME R & R AND WE'LL GO TO THE NEXT PHASE.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 9,
    :x 22,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :glass-door,
   :answers
   {:z 9,
    :x 25,
    :id "Door Zeta",
    :direction -0.0,
    :distance 8.0,
    :movement :right,
    :speed 2.0,
    :time 3.0}}
  {:name :glass-door,
   :answers
   {:z 9,
    :x 26,
    :id "Door Epsilon",
    :direction -0.0,
    :distance 8.0,
    :movement :left,
    :speed 2.0,
    :time 3.0}}
  {:name :text-screen,
   :answers
   {:direction 3.1269416873084,
    :protocol :hold,
    :text
    "POGGIO INSTITUTE\n================\n\nSEND A FUNCTION THAT TAKES A NUMBER n AND RETURNS THE COLOR\n(color n n n)\n",
    :parameter "fn",
    :text-color {:red 127, :green 255, :blue 0},
    :z 9,
    :x 29,
    :success-text "",
    :font-size 0.6,
    :transform "id",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring
    "Takes: A 1-argument function called fn.\nReturns: Modifies the cannons using fn.",
    :distance 40,
    :id "Transformer Epsilon",
    :target-ids []}}
  {:name :function-cannon,
   :answers
   {:direction 1.5707963267948966,
    :init-queue "(repeat 255)",
    :constraint "",
    :z 10,
    :velocity 75,
    :x 27,
    :transform-id "Transformer Epsilon",
    :mass 0.5,
    :queue? true,
    :distance 24,
    :id "Cannon Epsilon"}}
  {:name :function-cannon,
   :answers
   {:direction 1.5707963267948966,
    :init-queue "(repeat 0)",
    :constraint "",
    :z 10,
    :velocity 75,
    :x 28,
    :transform-id "Transformer Epsilon",
    :mass 0.5,
    :queue? true,
    :distance 24,
    :id "Cannon Zeta"}}
  {:name :text-screen,
   :answers
   {:direction 0.02394751692220761,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nTHE FIRST CANNON SPITS OUT 255\n\nTHE SECOND CANNON SPITS OUT 0",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 11,
    :x 27,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -1.5748946645047455,
    :protocol :none,
    :text
    "LIST OF WORDS USED BY MANAGEMENT THAT ARE STILL NOT REAL WORDS\n================\n\n1. SMOOSH.\n",
    :parameter "message",
    :text-color {:red 51, :green 153, :blue 255},
    :z 13,
    :x 29,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -1.589086969751717,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nYOU'VE DONE GOOD, MONKEY.\n\nYOU CAN MAKE FUNCTIONS MANUALLY, TOO!\n\nHERE'S HOW YOU CAN MAKE A FUNCTION THAT RAISES A NUMBER TO THE POWER OF 2.\n\n(function [x]\n  (multiply x x))\n\nOR HOW YOU CAN SMOOSH (YES, SMOOSH) TWO COLORS:\n\n(function [c1 c2]\n  (color (red c1) (green c2) (blue c3)))",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 13,
    :x 31,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :glass-door,
   :answers
   {:z 15,
    :x 31,
    :id "Door Delta",
    :direction -1.5821594740591876,
    :distance 8.0,
    :movement :down,
    :speed 2.0,
    :time 3.0}}
  {:name :text-screen,
   :answers
   {:direction -3.141592653589793,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nTHIS DOOR OPENS WHEN THE HOOP RECEIVES 3,4, AND 5.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 16,
    :x 24,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 3.131336602948126,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nIF YOU EVER GET STUCK BEHIND A DOOR, SEND true TO THE DOOR.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 16,
    :x 31,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -1.5669940637495459,
    :protocol :menus,
    :text
    "POGGIO INSTITUTE\n================\n\nSEND THE NUMBER OF THE CHOICE YOU WANT TO VIEW",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 17,
    :x 20,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform
    "{:start 0,\n 0\n {:label\n  \"THE FOLLOWING FUNCTIONS ARE USEFUL FOR BUILDING NEW FUNCTIONS\"\n  :states\n  [{:state 1, :label \"partial\"}\n   {:state 2, :label \"compose\"}\n   {:state 3, :label \"id\"}]},\n 1\n {:label\n  \"partial\\n\\nTAKES A 2-ARGUMENT FUNCTION AND A VALUE FOR THE FIRST ARGUMENT, AND RETURNS A 1-ARGUMENT FUNCTION THAT TAKES IN THE SECOND ARGUMENT.\\n\\n( (partial multiply 5) 2) RETURNS 10.\",\n  :states [{:state 0, :label \"Go Back\"}]},\n 2\n {:label\n  \"compose\\n\\nTAKES 2 1-ARGUMENT FUNCTIONS, f AND g, AND COMPOSES THEM TOGETHER INTO A 1-ARGUMENT FUNCTION OF THE FORM (f (g x)).\\n\\n( (compose repeat id) 5) RETURNS (repeat (id 5))\",\n  :states [{:state 0, :label \"Go Back\"}]}\n 3\n {:label\n  \"id\\n\\nRETURNS ANY VALUE GIVEN TO IT.\\n\\n(id 5) RETURNS 5\\n\\n(id red) RETURNS red\\n\\n(id id) RETURNS id\",\n  :states [{:state 0, :label \"Go Back\"}]}\n\n}\n",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "Help Menu Functions",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -1.6176370397108664,
    :protocol :hold,
    :text
    "POGGIO INSTITUTE\n================\n\nSEND A FUNCTION THAT INCREASES EACH NUMBER THE CANNON SPITS BY 2.",
    :parameter "fn",
    :text-color {:red 127, :green 255, :blue 0},
    :z 17,
    :x 21,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "id",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring
    "Takes: A 1-parameter function called fn.\nReturns: Changes the numbers Cannon Beta spits using fn.",
    :distance 40,
    :id "Transformer Beta",
    :target-ids []}}
  {:name :function-cannon,
   :answers
   {:direction -0.023805026185069942,
    :init-queue "(cycle [1 2 3])",
    :constraint "",
    :z 17,
    :velocity 75,
    :x 22,
    :transform-id "Transformer Beta",
    :mass 0.5,
    :queue? true,
    :distance 24,
    :id "Cannon Beta"}}
  {:name :globule-receiver,
   :answers
   {:z 17,
    :x 24,
    :id "",
    :direction -3.1319311184717313,
    :y 1,
    :target-ids ["Door Beta"],
    :protocol :open-on-pattern,
    :pattern ["3" "4" "5"]}}
  {:name :glass-door,
   :answers
   {:z 17,
    :x 31,
    :id "Door Gamma",
    :direction -1.5821594740591876,
    :distance 8.0,
    :movement :down,
    :speed 2.0,
    :time 3.0}}
  {:name :glass-door,
   :answers
   {:z 18,
    :x 25,
    :id "Door Beta",
    :direction -3.141592653589793,
    :distance 8.0,
    :movement :up,
    :speed 3.0,
    :time 0.0}}
  {:name :text-screen,
   :answers
   {:direction -3.0994235740133536,
    :protocol :none,
    :text " | |\n |X|\n | |",
    :parameter "message",
    :text-color {:red 51, :green 153, :blue 255},
    :z 18,
    :x 27,
    :success-text "",
    :font-size 2.0,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :globule-receiver,
   :answers
   {:z 18,
    :x 29,
    :id "Hoop Delta",
    :direction -1.5544934234762344,
    :y 1,
    :target-ids ["Door Delta"],
    :protocol :open-on-pattern,
    :pattern ["color 255 255 255"]}}
  {:name :globule-receiver,
   :answers
   {:z 18,
    :x 30,
    :id "Hoop Gamma",
    :direction -1.5544934234762344,
    :y 1,
    :target-ids ["Door Gamma"],
    :protocol :open-on-pattern,
    :pattern ["color 255 255 0"]}}
  {:name :text-screen,
   :answers
   {:direction -3.131542740696759,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nTHIS DOOR OPENS WHEN:\n\nTHE FIRST HOOP RECEIVES (color 255 255 255) (WHITE)\n\nTHE SECOND HOOP RECEIVES (color 255 255 0) (YELLOW)",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 18,
    :x 31,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :glass-door,
   :answers
   {:z 19,
    :x 21,
    :id "Door Alpha",
    :direction -1.5538487969884918,
    :distance 8.0,
    :movement :up,
    :speed 3.0,
    :time 0.0}}
  {:name :text-screen,
   :answers
   {:direction -3.0994235740133536,
    :protocol :none,
    :text " | |\nO|X|\n | |",
    :parameter "message",
    :text-color {:red 51, :green 153, :blue 255},
    :z 19,
    :x 27,
    :success-text "",
    :font-size 2.0,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :globule-receiver,
   :answers
   {:z 20,
    :x 20,
    :id "Hoop Alpha",
    :direction -1.5382299409700855,
    :y 1,
    :target-ids ["Door Alpha"],
    :protocol :open-on-pattern,
    :pattern ["green"]}}
  {:name :text-screen,
   :answers
   {:direction -1.5633337787596477,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nTHIS DOOR OPENS WHEN IT RECEIVES A GREEN GLOBULE.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 20,
    :x 22,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -0.00975578804551452,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nEMPLOYEES ARE REMINDED NOT TO PLAY TIC-TAC-TOE, POKER, BACKGAMMON, OR ANY OTHER GAME USING POGGIO INSTITUTE EQUIPMENT.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 20,
    :x 25,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -3.0994235740133536,
    :protocol :none,
    :text " | |\nO|X|\nX| |",
    :parameter "message",
    :text-color {:red 51, :green 153, :blue 255},
    :z 20,
    :x 27,
    :success-text "",
    :font-size 2.0,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :function-cannon,
   :answers
   {:direction 1.5707963267948966,
    :init-queue "(repeat 256)",
    :constraint "",
    :z 20,
    :velocity 75,
    :x 29,
    :transform-id "Transformer Gamma",
    :mass 0.5,
    :queue? true,
    :distance 24,
    :id "Cannon Delta"}}
  {:name :function-cannon,
   :answers
   {:direction 1.5707963267948966,
    :init-queue "(repeat 1)",
    :constraint "",
    :z 20,
    :velocity 75,
    :x 30,
    :transform-id "Transformer Gamma",
    :mass 0.5,
    :queue? true,
    :distance 24,
    :id "Cannon Gamma"}}
  {:name :text-screen,
   :answers
   {:direction 0.04321631880657707,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nTHE FIRST CANNON NORMALLY SPITS 256.\n\nTHE SECOND CANNON NORMALLY SPITS 1.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 21,
    :x 29,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -1.5551725981744198,
    :protocol :hold,
    :text
    "POGGIO INSTITUTE\n================\n\nSEND A FUNCTION THAT:\n\nMAKES THE FIRST CANNON SPIT (color 255 255 255)\n\nMAKES THE SECOND CANNON SPIT (color 255 255 0)",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 21,
    :x 31,
    :success-text "",
    :font-size 0.6,
    :transform "id",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring
    "Takes: A function called fn.\nReturns: Modifies what The cannons spit using fn.",
    :distance 40,
    :id "Transformer Gamma",
    :target-ids []}}
  {:name :function-cannon,
   :answers
   {:direction 1.5707963267948966,
    :init-queue "(repeat blue)",
    :constraint "",
    :z 22,
    :velocity 75,
    :x 20,
    :transform-id "Transformer Alpha",
    :mass 0.30000000000000004,
    :queue? true,
    :distance 24,
    :id "Cannon Alpha"}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nTHEN GIVE US BATHROOMS AND/OR PENGUINS.",
    :parameter "message",
    :text-color {:red 51, :green 153, :blue 255},
    :z 22,
    :x 25,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 3.1336246947282715,
    :protocol :menus,
    :text
    "POGGIO INSTITUTE\n================\n\nSEND THE NUMBER OF THE CHOICE YOU WANT TO VIEW",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 22,
    :x 31,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform
    "{:start 0,\n 0\n {:label\n  \"HERE'S SOME MORE FUNCTIONS FOR OUR SPECIAL LITTLE MONKEY.\"\n  :states\n  [{:state 1, :label \"partial3\"}\n   {:state 2, :label \"flip\"}\n   {:state 3, :label \"inc\"}\n   {:state 4, :label \"dec\"}]},\n 1\n {:label\n  \"partial3\\n\\nTAKES A 3-ARGUMENT FUNCTION AND A VALUE FOR THE FIRST ARGUMENT, AND RETURNS A 2-ARGUMENT FUNCTION THAT TAKES IN THE SECOND AND THIRD ARGUMENT.\\n\\n( (partial3 color 255) 0 0) RETURNS red.\",\n  :states [{:state 0, :label \"Go Back\"}]},\n 2\n {:label\n  \"flip\\n\\nFLIPS A 2-ARGUMENT FUNCTION.\\n\\n( (flip subtract) 3 2) RETURNS (subtract 2 3)\",\n  :states [{:state 0, :label \"Go Back\"}]}\n 3\n {:label\n  \"inc\\n\\nINCREASES A NUMBER BY 1.\\n\\n(inc 1) RETURNS 2\",\n  :states [{:state 0, :label \"Go Back\"}]}\n\n 4\n {:label\n  \"inc\\n\\nDECREASES A NUMBER BY 1.\\n\\n(dec 1) RETURNS 0\",\n  :states [{:state 0, :label \"Go Back\"}]}\n}\n",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "Help Menu Extras",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 0.021854443483362428,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nYOU CAN USE THE constantly FUNCTION TO MAKE A NEW FUNCTION THAT ALWAYS RETURNS THE SAME THING.\n\nEXAMPLES:\n\n( (constantly 1) 5) RETURNS 1.\n\n( (constantly green) red) RETURNS green.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 23,
    :x 18,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :model,
   :answers
   {:z-delta 6.0,
    :direction -1.0552473193359175,
    :model-name "Models/Penguin/Pingouin-NEW.scene",
    :z 24,
    :x 13,
    :y-delta 0.0,
    :x-delta 2.0,
    :id "",
    :collidable? false}}
  {:name :text-screen,
   :answers
   {:direction -3.133294088905124,
    :protocol :hold,
    :text
    "POGGIO INSTITUTE\n================\n\nSEND A FUNCTION THAT TURNS THE GLOBULES INTO GREEN.\n\n",
    :parameter "fn",
    :text-color {:red 127, :green 255, :blue 0},
    :z 24,
    :x 19,
    :success-text "",
    :font-size 0.6,
    :transform "(constantly blue)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring
    "Takes: A 1-argument function called fn.\nReturns: Modifies what the cannon spits out with fn.",
    :distance 40,
    :id "Transformer Alpha",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -0.010256050641667055,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nDEAR BOSSMAN. \n\n\nHERE ARE MY FOLLOWING COMPLAINTS:\n\n1. I THINK THE CANNON IS BROKE. I CAN'T GIVE IT A LIST. WHAT'S UP WITH THAT?\n\n2. THE LACK OF BATHROOMS IS OUTRAGEOUS. \n\nSINCERELY,\n\nIAN",
    :parameter "message",
    :text-color {:red 51, :green 153, :blue 255},
    :z 24,
    :x 21,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :glass-door,
   :answers
   {:z 25,
    :x 15,
    :id "",
    :direction 0.024385409172718538,
    :distance 0.0,
    :movement :up,
    :speed 0.0,
    :time 0.0}}
  {:name :text-screen,
   :answers
   {:direction -1.5761726190806056,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nUNFORTUNATE NEWS:\n\nDUE TO PENGUIN REPLICATION COMPLICATIONS, THE ZOO IS CLOSED FOR NOW.\n\nSORRY.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 25,
    :x 16,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -1.5600053787569956,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\n<=== ZOO\n\n===> TRAINING FACILITIES",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 27,
    :x 20,
    :success-text "",
    :font-size 0.9,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}]}
