{:loc [1 1],
 :dir -0.02197448429666256,
 :walls
 #{[8 7] [11 10] [1 0] [2 2] [3 3] [7 7] [11 11] [0 0] [6 7] [0 1]
   [3 5] [5 7] [10 12] [0 2] [2 5] [4 7] [5 8] [10 13] [0 3] [1 4]
   [2 6] [3 7] [5 9] [8 12] [10 14] [0 4] [5 10] [7 12] [8 13] [10 15]
   [5 11] [6 12] [8 14] [10 16] [11 17] [5 12] [11 18] [4 12] [9 17]
   [11 19] [8 17] [11 20] [3 13] [7 17] [9 19] [11 21] [3 14] [5 16]
   [6 17] [9 20] [11 22] [2 14] [4 16] [11 23] [1 13] [3 16] [8 21]
   [10 23] [2 16] [6 20] [7 21] [8 22] [9 23] [0 14] [5 20] [8 23]
   [0 15] [4 20] [0 16] [3 20] [0 17] [2 20] [0 18] [0 19] [1 20]
   [0 20] [10 3] [11 4] [7 1] [8 2] [9 3] [11 5] [6 1] [8 3] [11 6]
   [5 1] [7 3] [11 7] [3 0] [4 1] [11 8] [3 1] [7 5] [8 6] [11 9]
   [2 0]},
 :wall-mat "Textures/grate1.png",
 :widgets
 [{:name :text-screen,
   :answers
   {:direction -3.1307822639156866,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nDEAR EMPLOYEES:\n\nSTOP FILLING THE HALLS WITH BALLPITS.\n\nIT ISN'T CUTE, IT'S OBNOXIOUS.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 1,
    :x 2,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :id "",
    :target-ids []}}
  {:name :function-cannon,
   :answers
   {:direction -0.0,
    :init-queue "[(color 0 0 0)]",
    :constraint "",
    :z 2,
    :velocity 75,
    :x 3,
    :transform-id "",
    :mass 0.5,
    :queue? true,
    :id "hidden cannon 2"}}
  {:name :globule-receiver,
   :answers
   {:z 2,
    :x 7,
    :id "",
    :direction -3.1307822639156866,
    :y 0,
    :target-ids ["hidden cannon 1"],
    :protocol :pass,
    :pattern []}}
  {:name :text-screen,
   :answers
   {:direction 3.126326664043013,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nHEY SPENCE, LOOK AT THAT.\n\nWE'RE \"OBNOXIOUS\" NOW!\n\nMOVIN' ON UP!",
    :parameter "message",
    :text-color {:red 51, :green 153, :blue 255},
    :z 3,
    :x 2,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :id "",
    :target-ids []}}
  {:name :glass-door,
   :answers
   {:z 3,
    :x 4,
    :id "",
    :direction 1.5707963267948966,
    :distance 0.0,
    :movement :up,
    :speed 0.0,
    :time 0.0}}
  {:name :glass-door,
   :answers
   {:z 3,
    :x 5,
    :id "",
    :direction 1.5707963267948966,
    :distance 0.0,
    :movement :up,
    :speed 0.0,
    :time 0.0}}
  {:name :glass-door,
   :answers
   {:z 3,
    :x 6,
    :id "",
    :direction 1.5707963267948966,
    :distance 0.0,
    :movement :up,
    :speed 0.0,
    :time 0.0}}
  {:name :text-screen,
   :answers
   {:direction -3.0988379753055453,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nDON'T BE AFRAID TO PERUSE THE MODULES AND FUNCTIONS.\n\nREADING RARELY HURTS. ",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 4,
    :x 10,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :id "",
    :target-ids []}}
  {:name :glass-door,
   :answers
   {:z 5,
    :x 4,
    :id "",
    :direction 1.5707963267948966,
    :distance 0.0,
    :movement :up,
    :speed 0.0,
    :time 0.0}}
  {:name :glass-door,
   :answers
   {:z 5,
    :x 5,
    :id "",
    :direction 1.5707963267948966,
    :distance 0.0,
    :movement :up,
    :speed 0.0,
    :time 0.0}}
  {:name :glass-door,
   :answers
   {:z 5,
    :x 6,
    :id "",
    :direction 1.5707963267948966,
    :distance 0.0,
    :movement :up,
    :speed 0.0,
    :time 0.0}}
  {:name :globule-receiver,
   :answers
   {:z 6,
    :x 3,
    :id "",
    :direction -0.0,
    :y 0,
    :target-ids ["hidden cannon 2"],
    :protocol :pass,
    :pattern []}}
  {:name :function-cannon,
   :answers
   {:direction 3.13128374044355,
    :init-queue "",
    :constraint "",
    :z 6,
    :velocity 75,
    :x 7,
    :transform-id "",
    :mass 0.5,
    :queue? true,
    :id "hidden cannon 1"}}
  {:name :text-screen,
   :answers
   {:direction 0.02259502408669883,
    :protocol :hold,
    :text
    "POGGIO INSTITUTE\n================\n\nYOU CAN ALSO SEND FUNCTIONS.\n\nTHIS CONSOLE MODIFIES THE VALUES THE CANNONS SPIT OUT.\n\nSEND A FUNCTION THAT INCREASES THE VALUES BY 1, LIKE inc.\n\nDON'T OVERTHINK IT.",
    :parameter "fn",
    :text-color {:red 127, :green 255, :blue 0},
    :z 7,
    :x 9,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring
    "Takes: A 1-parameter function called fn.\nReturns: Modifiers cannon using fn.",
    :id "Transformer 1",
    :target-ids []}}
  {:name :globule-receiver,
   :answers
   {:z 8,
    :x 6,
    :id "Hoop 3",
    :direction -1.5849463257329033,
    :y 0,
    :target-ids ["Door 3"],
    :protocol :open-on-pattern,
    :pattern ["9"]}}
  {:name :globule-receiver,
   :answers
   {:z 8,
    :x 7,
    :id "Hoop 2",
    :direction -1.576059436092492,
    :y 0,
    :target-ids ["Door 2"],
    :protocol :open-on-pattern,
    :pattern ["4"]}}
  {:name :globule-receiver,
   :answers
   {:z 8,
    :x 8,
    :id "Hoop 1",
    :direction -1.6492066655335385,
    :y 0,
    :target-ids ["Door 1"],
    :protocol :open-on-pattern,
    :pattern ["2"]}}
  {:name :function-cannon,
   :answers
   {:direction 1.5707963267948966,
    :init-queue "(repeat 8)",
    :constraint "",
    :z 11,
    :velocity 75,
    :x 6,
    :transform-id "Transformer 1",
    :mass 0.5,
    :queue? true,
    :id "Cannon 3"}}
  {:name :function-cannon,
   :answers
   {:direction 1.5707963267948966,
    :init-queue "(repeat 3)",
    :constraint "",
    :z 11,
    :velocity 75,
    :x 7,
    :transform-id "Transformer 1",
    :mass 0.5,
    :queue? true,
    :id "Cannon 2"}}
  {:name :function-cannon,
   :answers
   {:direction 1.5707963267948966,
    :init-queue "(repeat 1)",
    :constraint "",
    :z 11,
    :velocity 75,
    :x 8,
    :transform-id "Transformer 1",
    :mass 0.5,
    :queue? true,
    :id "Cannon 1"}}
  {:name :glass-door,
   :answers
   {:z 12,
    :x 9,
    :id "Door 1",
    :direction 1.5707963267948966,
    :distance 8.0,
    :movement :left,
    :speed 4.0,
    :time 0.0}}
  {:name :globule-receiver,
   :answers
   {:z 13,
    :x 4,
    :id "Hoop 4",
    :direction -0.0,
    :y 0,
    :target-ids ["Door 4"],
    :protocol :open-on-pattern,
    :pattern ["blue"]}}
  {:name :function-cannon,
   :answers
   {:direction -3.1328209487453504,
    :init-queue "(flatten (repeat [2 4 6]))",
    :constraint "",
    :z 13,
    :velocity 75,
    :x 7,
    :transform-id "Transformer 2",
    :mass 0.5,
    :queue? true,
    :id "2-4-6 Cannon"}}
  {:name :glass-door,
   :answers
   {:z 13,
    :x 9,
    :id "Door 2",
    :direction 1.5707963267948966,
    :distance 8.0,
    :movement :right,
    :speed 4.0,
    :time 0.0}}
  {:name :globule-receiver,
   :answers
   {:z 14,
    :x 4,
    :id "Hoop 5",
    :direction 0.016805140515041995,
    :y 0,
    :target-ids ["Door 5"],
    :protocol :open-on-pattern,
    :pattern ["red"]}}
  {:name :function-cannon,
   :answers
   {:direction -3.123412838516815,
    :init-queue "(flatten (repeat [1 3 5]))",
    :constraint "",
    :z 14,
    :velocity 75,
    :x 7,
    :transform-id "Transformer 2",
    :mass 0.5,
    :queue? true,
    :id "1-3-5 Cannon"}}
  {:name :glass-door,
   :answers
   {:z 14,
    :x 9,
    :id "Door 3",
    :direction 1.5707963267948966,
    :distance 8.0,
    :movement :up,
    :speed 4.0,
    :time 0.0}}
  {:name :text-screen,
   :answers
   {:direction -0.01169537316568895,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nIF YOU EVER NEED TO CONSTRUCT MULTI-PARAMETER FUNCTIONS,\nOR WANT TO GIVE A FUNCTION A NAME, USE THE NEW BUTTON AND SAVE THE FUNCTION.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 15,
    :x 1,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :id "",
    :target-ids []}}
  {:name :glass-door,
   :answers
   {:z 15,
    :x 2,
    :id "Door 5",
    :direction -0.049958395721942765,
    :distance 8.0,
    :movement :right,
    :speed 4.0,
    :time 0.0}}
  {:name :glass-door,
   :answers
   {:z 15,
    :x 3,
    :id "Door 4",
    :direction -0.0,
    :distance 8.0,
    :movement :left,
    :speed 3.0,
    :time 0.0}}
  {:name :text-screen,
   :answers
   {:direction -1.5439210787101398,
    :protocol :hold,
    :text
    "POGGIO INSTITUTE\n================\n\nSEND A FUNCTION TO CORRECTLY MODIFY THESE TWO CANNONS.",
    :parameter "fn",
    :text-color {:red 127, :green 255, :blue 0},
    :z 15,
    :x 8,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x]\n  x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring
    "Takes: A 1-parameter function called fn.\nReturns: Modifies the output of the cannons.",
    :id "Transformer 2",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -0.0,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nI, FOR ONE, MADE THIS FUNCTION:\n\nFUNCTION NAME: always-2\n\nPARAMETERS: c\n\nCODE: \n  (if (equal? (r-value c) 2)\n     2\n     2)\n\n\nBASK IN MY GENIUS.",
    :parameter "message",
    :text-color {:red 51, :green 153, :blue 255},
    :z 16,
    :x 1,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n \nHEY IAN. YOU KNOW?\n\nI DON'T CARE IF BOSSMAN DOESN'T THINK US FILLING THE HALLS WITH BALLPITS ISN'T CUTE.\n\nBECAUSE I THINK IT MAKES US FRANKLY...\n\n(o_o)\n(o_o)>~D-D\n(~D_D)\n\n....BALLIN'",
    :parameter "message",
    :text-color {:red 51, :green 153, :blue 255},
    :z 16,
    :x 6,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nYOU CAN USE if TO DO DIFFERENT THINGS DEPENDING\nON A VALUE, LIKE\n\n(function [x]\n  (if (even? x)\n     2\n     3))\n\nIS A FUNCTION THAT RETURNS 2 WHEN x is EVEN AND 3 WHEN x IS ODD.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 16,
    :x 9,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :id "",
    :target-ids []}}
  {:name :function-cannon,
   :answers
   {:direction -1.546410917622178,
    :init-queue "",
    :constraint "color",
    :z 17,
    :velocity 75,
    :x 2,
    :transform-id "",
    :mass 0.5,
    :queue? false,
    :id "First Cannon"}}
  {:name :function-cannon,
   :answers
   {:direction -1.5707963267948966,
    :init-queue "",
    :constraint "number",
    :z 17,
    :velocity 75,
    :x 4,
    :transform-id "Color To Number Transform",
    :mass 0.5,
    :queue? true,
    :id "Number Cannon 1"}}
  {:name :globule-receiver,
   :answers
   {:z 17,
    :x 5,
    :id "Last Hoop",
    :direction -1.526183091748594,
    :y 0,
    :target-ids ["Left Sliding Door" "Right Sliding Door"],
    :protocol :open-on-pattern,
    :pattern ["red" "blue"]}}
  {:name :text-screen,
   :answers
   {:direction -0.0,
    :protocol :hold,
    :text "POGGIO INSTITUTE\n================\n",
    :parameter "fn",
    :text-color {:red 127, :green 255, :blue 0},
    :z 18,
    :x 1,
    :success-text "",
    :font-size 0.6,
    :transform
    "(function [c]\n  (if (color-equal? c red)\n    2\n    2))",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring
    "Takes: A 1-parameter function called fn.\nReturns: Converts colors from the first cannon into numbers.",
    :id "Color To Number Transform",
    :target-ids []}}
  {:name :glass-door,
   :answers
   {:z 18,
    :x 6,
    :id "Right Sliding Door",
    :direction -3.077849341057106,
    :distance 8.0,
    :movement :left,
    :speed 2.0,
    :time 3.0}}
  {:name :glass-door,
   :answers
   {:z 18,
    :x 9,
    :id "Exit Door",
    :direction -3.1259689249693166,
    :distance 8.0,
    :movement :up,
    :speed 4.0,
    :time 0.0}}
  {:name :text-screen,
   :answers
   {:direction -0.01169537316568895,
    :protocol :hold,
    :text "POGGIO INSTITUTE\n================\n",
    :parameter "fn",
    :text-color {:red 127, :green 255, :blue 0},
    :z 19,
    :x 1,
    :success-text "",
    :font-size 0.6,
    :transform "(function [n]\n    blue)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring
    "Takes: A 1-parameter function called fn.\nReturns: Converts numbers from the second cannon into colors.",
    :id "Number To Color Transform",
    :target-ids []}}
  {:name :globule-receiver,
   :answers
   {:z 19,
    :x 2,
    :id "First Pass Hoop",
    :direction 1.5707963267948966,
    :y 0,
    :target-ids ["Number Cannon 1"],
    :protocol :pass,
    :pattern []}}
  {:name :globule-receiver,
   :answers
   {:z 19,
    :x 4,
    :id "Second Hoop",
    :direction 1.5707963267948966,
    :y 0,
    :target-ids ["Color Cannon 1"],
    :protocol :pass,
    :pattern []}}
  {:name :function-cannon,
   :answers
   {:direction 1.5707963267948966,
    :init-queue "",
    :constraint "color",
    :z 19,
    :velocity 75,
    :x 5,
    :transform-id "Number To Color Transform",
    :mass 0.5,
    :queue? true,
    :id "Color Cannon 1"}}
  {:name :glass-door,
   :answers
   {:z 19,
    :x 6,
    :id "Left Sliding Door",
    :direction -3.115957245068116,
    :distance 8.0,
    :movement :right,
    :speed 2.0,
    :time 3.0}}
  {:name :text-screen,
   :answers
   {:direction -3.1322032581633916,
    :protocol :open,
    :text
    "POGGIO INSTITUTE\n================\n\nSEND true TO EXIT LEVEL.",
    :parameter "exit-code",
    :text-color {:red 127, :green 255, :blue 0},
    :z 19,
    :x 8,
    :success-text "GOOD BYE.",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? true,
    :success? "exit-code",
    :error-text "Send true to open exit.",
    :docstring
    "Takes: a boolean b.\nReturns: Opens exit when b is true.",
    :id "Exit Console",
    :target-ids ["Exit Door"]}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nWE ARE STILL CRUNCHING DATA FROM THE PAPERS WE FOUND ON YOUR BODY. WE WILL INFORM YOU OF OUR ASSESSMENTS WHEN OUR COMPUTERS ARE HEADQUARTERS STOP SMOKING.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 20,
    :x 7,
    :success-text "",
    :font-size 0.6,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 3.115167088329975,
    :protocol :none,
    :text "EXIT",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 20,
    :x 8,
    :success-text "",
    :font-size 2.0,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :id "",
    :target-ids []}}]}
