{:loc [1 30],
 :dir 1.5707963267948966,
 :walls
 #{[1 32] [6 5] [11 10] [12 11] [15 14] [17 16] [18 17] [0 31] [6 6]
   [11 11] [15 15] [19 19] [0 32] [6 7] [11 12] [15 16] [18 19] [6 8]
   [15 17] [16 18] [17 19] [6 9] [7 10] [10 13] [6 10] [10 14] [6 11]
   [8 13] [10 15] [6 12] [7 13] [6 13] [9 16] [6 14] [8 16] [5 14]
   [7 16] [4 14] [6 16] [5 16] [3 15] [5 17] [3 16] [5 18] [3 17]
   [5 19] [6 20] [7 21] [3 18] [5 20] [6 21] [7 22] [3 19] [7 23]
   [19 3] [2 19] [3 20] [7 24] [18 3] [19 4] [7 25] [15 1] [16 2]
   [17 3] [19 5] [20 6] [1 19] [7 26] [14 1] [16 3] [20 7] [1 20]
   [3 23] [4 24] [6 26] [13 1] [17 5] [20 8] [1 21] [3 24] [6 27]
   [12 1] [16 5] [18 7] [1 22] [2 24] [6 28] [16 6] [19 9] [1 23]
   [2 25] [6 29] [10 1] [11 2] [16 7] [19 10] [20 11] [21 12] [2 26]
   [6 30] [11 3] [15 7] [16 8] [17 9] [21 13] [2 27] [6 31] [9 2]
   [16 9] [17 10] [21 14] [2 28] [3 29] [11 5] [13 7] [16 10] [17 11]
   [18 12] [20 14] [21 15] [3 30] [5 32] [8 3] [11 6] [12 7] [15 10]
   [17 12] [21 16] [1 28] [4 32] [7 3] [12 8] [14 10] [17 13] [3 32]
   [8 5] [9 6] [10 7] [12 9] [13 10] [16 13] [17 14] [20 17] [0 29]
   [2 32] [6 4] [8 6] [10 8] [11 9] [12 10] [17 15] [20 18] [0 30]},
 :wall-mat "Textures/paper1.jpg",
 :widgets
 [{:name :function-cannon,
   :answers
   {:direction -1.5707963267948966,
    :init-queue "",
    :constraint "",
    :z 2,
    :velocity 50,
    :x 13,
    :transform-id "",
    :interactive? true,
    :mass 0.5,
    :queue? false,
    :inspection "",
    :distance 24,
    :id "Earth Cannon 2"}}
  {:name :text-screen,
   :answers
   {:direction -3.141592653589793,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nOH...WE THOUGHT YOU'D TAKE LONGER TO SOLVE THE PUZZLES.\n\nWELL, WE DIDN'T FIX THE ZOO, AND WE HAVEN'T FIXED YOUR PLANET YET EITHER.\n\nUM...WOW...GUESS ENTERTAIN YOURSELF TILL WE DO?",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 3,
    :x 10,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :model,
   :answers
   {:z-delta 0.0,
    :direction 1.5707963267948966,
    :model-name "Models/Earth/earth.scene",
    :z 4,
    :x 13,
    :y-delta 5.0,
    :mass 0.5,
    :x-delta 0.0,
    :id "",
    :collidable? true}}
  {:name :glass-door,
   :answers
   {:z 6,
    :x 7,
    :id "Door Prime",
    :direction -1.4994888620096063,
    :distance 8.0,
    :movement :down,
    :speed 2.0,
    :time 3.0}}
  {:name :function-cannon,
   :answers
   {:direction 1.5405025668761214,
    :init-queue "",
    :constraint "",
    :z 6,
    :velocity 50,
    :x 13,
    :transform-id "",
    :interactive? true,
    :mass 0.5,
    :queue? false,
    :inspection "",
    :distance 24,
    :id "Earth Cannon 1"}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nIF YOU ENJOYED PROGRAMMING IN POGGIO, HERE ARE SOME OTHER FUNCTIONAL PROGRAMMING LANGUAGES TO TRY OUT\n\nTHEY OUGHT TO BIDE YOU OVER TILL WE GET THIS PLANET ISSUE FIXED UP...",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 6,
    :x 18,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text "SECRET ROOM",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 7,
    :x 8,
    :success-text "",
    :font-size 2.0,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :glass-door,
   :answers
   {:z 7,
    :x 14,
    :id "",
    :direction 1.5707963267948966,
    :distance 0.0,
    :movement :up,
    :speed 0.0,
    :time 0.0}}
  {:name :text-screen,
   :answers
   {:direction 0.027552081247758736,
    :protocol :none,
    :text
    "SCALA\n================\n\nRESOURCES:\n\nwww.simplyscala.com\n\nCODE-SNIPPET: \n\nList(1,2,3).foldRight(0)(_ + _)\nRETURNS THE SUM OF THE LIST.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 7,
    :x 17,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -3.1292981911116406,
    :protocol :none,
    :text
    "RUBY\n================\n\nRESOURCES:\n\nrubymonk.com\n\nCODE-SNIPPET: \n\n[1,2,3,4].combination(2)\n\nRETURNS ALL POSSIBLE 2-SIZED COMBINATIONS OF THE ARRAY\n\n[[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]]",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 7,
    :x 19,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :model,
   :answers
   {:z-delta 0.0,
    :direction -1.6052654277944047,
    :model-name "Models/Penguin/Pingouin-NEW.scene",
    :z 8,
    :x 14,
    :y-delta 0.0,
    :mass 0.0,
    :x-delta 0.0,
    :id "",
    :collidable? false}}
  {:name :model,
   :answers
   {:z-delta 0.0,
    :direction -2.1332942578639695,
    :model-name "Models/Penguin/Pingouin-NEW.scene",
    :z 8,
    :x 15,
    :y-delta 0.0,
    :mass 0.0,
    :x-delta 0.0,
    :id "",
    :collidable? false}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text
    "HASKELL\n================\n\nRESOURCES:\n\ntryhaskell.org\n\nlearnyouahaskell.com\n^MY FAVORITE PROGRAMMING BOOK\n\nCODE-SNIPPET: \n\nfib = 1:1: zipWith (+) fib (tail fib)\n\nRETURNS AN INFINITE LIST OF FIBONACCI NUMBERS",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 8,
    :x 17,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text
    "CLOJURE\n================\n\n(THIS IS WHAT POGGIO WAS PROGRAMMED IN)\n\nRESOURCES:\n\ntryclj.com\n\nwww.4clojure.com\n\nCODE-SNIPPET: \n\n(repeatedly #(rand-int 10))\n\nRETURNS AN INFINITE LIST OF RANDOM NUMBERS BETWEEN 0-9\n",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 8,
    :x 19,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :globule-receiver,
   :answers
   {:z 9,
    :x 10,
    :id "Hoop Prime",
    :direction -1.5779390624643101,
    :y 1,
    :target-ids ["Door Prime"],
    :protocol :open-on-pattern,
    :pattern ["red" "red" "green" "red" "green"]}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text "HI\n\n:-D",
    :parameter "message",
    :text-color {:red 51, :green 153, :blue 255},
    :z 9,
    :x 14,
    :success-text "",
    :font-size 2.5,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -3.119974400353286,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nTHE DOOR OPENS WHEN THE HOOP RECEIVES red, red, green, red, green.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 10,
    :x 10,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -1.5221621412898891,
    :protocol :hold,
    :text
    "POGGIO INSTITUTE\n================\n\nSEND A FUNCTION THAT:\n\nRETURNS red WHEN GIVEN A PRIME NUMBER\n\nRETURNS green WHEN GIVEN A NON-PRIME NUMBER.\n\n\"DON'T LET ME DOWN.\"\n~ YOUR MOTHER.",
    :parameter "fn",
    :text-color {:red 127, :green 255, :blue 0},
    :z 11,
    :x 7,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "id",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring
    "Takes: a 1-argument function called fn.\nReturns: Modifies what the cannon spits using fn.",
    :distance 40,
    :id "Prime Transformer",
    :target-ids []}}
  {:name :function-cannon,
   :answers
   {:direction 1.5707963267948966,
    :init-queue "(cycle [2 17 4 3 6])",
    :constraint "",
    :z 11,
    :velocity 75,
    :x 10,
    :transform-id "Prime Transformer",
    :interactive? true,
    :mass 0.5,
    :queue? true,
    :inspection "",
    :distance 24,
    :id "Prime Cannon"}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nOR JUST SEARCH FOR FUNCTIONAL PROGRAMMING LANGUAGES AND ENJOY THE JOURNEY.\n\nHERE ARE SOME OTHER LANGUAGES YOU MIGHT WANT TO LOOK AT:\n\nPython\nRacket\nScheme\nCommon Lisp\nML\n",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 11,
    :x 18,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -0.02757921239974079,
    :protocol :menus,
    :text
    "POGGIO INSTITUTE\n================\n\nSEND THE NUMBER OF YOUR CHOICE\n",
    :parameter "choice",
    :text-color {:red 127, :green 255, :blue 0},
    :z 12,
    :x 7,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform
    "{:start 0\n  0\n   {:label \"THE FOLLOWING INFO MAY BE HELPFUL.\"\n     :states [{:label \"Prime Numbers\" :state 1}\n                  {:label \"remainder\" :state 2}]}\n  1\n    {:label \"Prime Numbers\\n\\nPrime numbers are integers greater than 1 who are evenly divided only by 1 and itself.\\n\\n1,4,6, AND 9 ARE NOT PRIME.\\n\\n2,5, AND 7 ARE PRIME.\"\n      :states [{:label \"GO BACK\" :state 0}]}\n  2\n    {:label \"remainder\\n\\n(remainder x y) RETURNS THE REMAINDER OF DIVIDING x BY y.\\n\\n(remainder 5 2) RETURNS 1.\"\n      :states [{:label \"GO BACK\" :state 0}]}}",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "Help Menu",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nFEEL FREE TO EXPLORE THE SANDBOX TO PLAY WITH THE WIDGETS.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 13,
    :x 20,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -3.129897280424104,
    :protocol :none,
    :text "POGGIO INSTITUTE\n================\n\nRATS.",
    :parameter "message",
    :text-color {:red 51, :green 153, :blue 255},
    :z 14,
    :x 9,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -1.4433910112562327,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nSWEET! WE MADE IT!\n\nALL RIGHT! SECRET ROOM HERE WE COME! HERE'S HOPING THE SECRET ROOM IS A BATHROOM!",
    :parameter "message",
    :text-color {:red 51, :green 153, :blue 255},
    :z 15,
    :x 4,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -3.1025880553849885,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nCOMPLETE THIS LAST PUZZLE TO GAIN ACCESS TO THE SECRET ROOM.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 15,
    :x 9,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :none,
    :text "EXIT",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 16,
    :x 18,
    :success-text "",
    :font-size 2.0,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction 1.5707963267948966,
    :protocol :open,
    :text "POGGIO INSTITUTE\n================\nSEND true TO EXIT.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 16,
    :x 20,
    :success-text "\nGOOD BYE.",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? true,
    :success? "message",
    :error-text "Just send true...",
    :docstring
    "Takes: a boolean called message.\nReturns: Opens the door if message is true.",
    :distance 40,
    :id "Exit Transformer",
    :target-ids ["Exit Door"]}}
  {:name :glass-door,
   :answers
   {:z 17,
    :x 19,
    :id "Exit Door",
    :direction 1.5707963267948966,
    :distance 8.0,
    :movement :up,
    :speed 4.0,
    :time 0.0}}
  {:name :sound-barrier,
   :answers
   {:z 18,
    :x 4,
    :id "",
    :direction -1.5621758506827603,
    :target-ids ["Music Box 1"]}}
  {:name :glass-door,
   :answers
   {:z 19,
    :x 4,
    :id "Door 2",
    :direction -1.6124389058934852,
    :distance 8.0,
    :movement :right,
    :speed 1.0,
    :time 2.0}}
  {:name :glass-door,
   :answers
   {:z 20,
    :x 4,
    :id "Door 1",
    :direction -1.6124389058934852,
    :distance 8.0,
    :movement :left,
    :speed 1.0,
    :time 2.0}}
  {:name :ball-stereo,
   :answers
   {:z 21,
    :x 2,
    :id "Stereo 2",
    :target-ids ["Door 2"],
    :protocol :open-on-pattern,
    :transformer-id "",
    :pattern ["green"]}}
  {:name :text-screen,
   :answers
   {:direction -1.5941565626167713,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\n\nTHESE DOORS OPEN WHEN:\n\nTHE FIRST STEREO SPITS blue\n\nTHE SECOND STEREO SPIT green",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 21,
    :x 5,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :ball-stereo,
   :answers
   {:z 22,
    :x 2,
    :id "Stereo 1",
    :target-ids ["Door 1"],
    :protocol :open-on-pattern,
    :transformer-id "",
    :pattern ["blue"]}}
  {:name :music-box,
   :answers
   {:direction 1.5707963267948966,
    :stereos ["Stereo 1" "Stereo 2"],
    :z 22,
    :x 3,
    :muted? false,
    :interactive? true,
    :queue-init "",
    :queue? true,
    :transformer-id "Transformer 2",
    :distance 24,
    :id "Music Box 1"}}
  {:name :globule-receiver,
   :answers
   {:z 22,
    :x 6,
    :id "Hoop 3",
    :direction -1.633215136790854,
    :y 1,
    :target-ids ["Music Box 1"],
    :protocol :pass,
    :pattern []}}
  {:name :text-screen,
   :answers
   {:direction -0.012421721321955117,
    :protocol :hold,
    :text
    "POGGIO INSTITUTE\n================\n\nSEND A FUNCTION THAT CONVERTS A COLOR INTO A NOTE\n\nWHEN d IS PLAYED, A green BALL IS SPITTED.\nWHEN e IS PLAYED, A blue BALL IS SPITTED.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 23,
    :x 4,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(constantly c)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "Transformer 2",
    :target-ids []}}
  {:name :function-cannon,
   :answers
   {:direction 1.5707963267948966,
    :init-queue "",
    :constraint "",
    :z 24,
    :velocity 75,
    :x 6,
    :transform-id "",
    :interactive? true,
    :mass 0.5,
    :queue? true,
    :distance 24,
    :id "Cannon 3"}}
  {:name :globule-receiver,
   :answers
   {:z 25,
    :x 3,
    :id "Hoop 1",
    :direction -1.4793851249346157,
    :y 1,
    :target-ids ["Cannon 2"],
    :protocol :pass,
    :pattern []}}
  {:name :function-cannon,
   :answers
   {:direction -0.037020115873930025,
    :init-queue "",
    :constraint "",
    :z 25,
    :velocity 75,
    :x 4,
    :transform-id "",
    :interactive? true,
    :mass 0.5,
    :queue? true,
    :distance 24,
    :id "Cannon 2"}}
  {:name :globule-receiver,
   :answers
   {:z 25,
    :x 6,
    :id "Hoop 2",
    :direction -3.115167088329975,
    :y 1,
    :target-ids ["Cannon 3"],
    :protocol :pass,
    :pattern []}}
  {:name :function-cannon,
   :answers
   {:direction 1.5707963267948966,
    :init-queue "",
    :constraint "",
    :z 27,
    :velocity 75,
    :x 3,
    :transform-id "Transformer 1",
    :interactive? false,
    :mass 0.5,
    :queue? false,
    :inspection "",
    :distance 24,
    :id "Cannon 1"}}
  {:name :text-screen,
   :answers
   {:direction 0.0425275346197842,
    :protocol :hold,
    :text
    "POGGIO INSTITUTE\n================\n\nSEND A FUNCTION THAT CONVERTS A BOOLEAN INTO A COLOR.\n",
    :parameter "fn",
    :text-color {:red 127, :green 255, :blue 0},
    :z 28,
    :x 3,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(constantly blue)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring
    "Takes: a 1-argument function called fn.\nReturns: Modifies what the cannon spits using fn.",
    :distance 40,
    :id "Transformer 1",
    :target-ids []}}
  {:name :text-screen,
   :answers
   {:direction -1.5370253871899826,
    :protocol :none,
    :text
    "POGGIO INSTITUTE\n================\nSINCE WE'VE NOW DETERMINED YOU HAVE THE INTELLIGENCE AND CALM MIND TO HEAR WHY WE BROUGHT YOU HERE, YOU'RE FREE TO ENTER OUR \"SECRET\" ROOM. \n\nONCE YOU UNLOCK IT.",
    :parameter "message",
    :text-color {:red 127, :green 255, :blue 0},
    :z 29,
    :x 1,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring "",
    :distance 40,
    :id "",
    :target-ids []}}
  {:name :cellular-automaton,
   :answers
   {:direction 0.16789592325037456,
    :protocol :rule,
    :z 29,
    :init-id "",
    :x 4,
    :precompute? false,
    :rule-id "",
    :target-id "Cannon 1",
    :row-id "",
    :pair-id "",
    :generations-id "",
    :end-protocol :pass-last-row,
    :id "Cell Wall",
    :rule "(function [left old right] \n   (not old))"}}
  {:name :text-screen,
   :answers
   {:direction -0.010581615621075877,
    :protocol :pass,
    :text
    "POGGIO INSTITUTE\n================\n\nSEND A RULE FUNCTION TO BUILD OUT THE CELLS IN THE CELL WALL",
    :parameter "rule",
    :text-color {:red 127, :green 255, :blue 0},
    :z 30,
    :x 4,
    :success-text "",
    :font-size 0.6,
    :split? false,
    :transform "(function [x] x)",
    :end-level? false,
    :success? "",
    :error-text "",
    :docstring
    "Takes: a 3-argument function called rule.\nReturns: Populates the cell wall using rule.",
    :distance 40,
    :id "Cell Wall Transformer",
    :target-ids ["Cell Wall"]}}]}
